# XBox 360 wired controller
teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    deadman_buttons: []  # No deadman buttons
    axis_mappings:
      -
        axis: 1  # Right thumb (up/down)
        target: linear.x
        scale: 0.05
        offset: 0.0
      -
        axis: 0  # Right thumb stick (left/right)
        target: angular.z
        scale: 1
        offset: 0.0
